CREATE TABLE livros {
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(100) NOT NULL,
  autor VARCHAR(100),
  capa VARCHAR(255),
  arquivo VARCHAR(255),
  data_upload TIMESTAMP DEFAULT CURRENT_TIMESTAMP
};